version: '3.9'

services:
  backend1:
    build:
      context: ./backend/backend1
      dockerfile: Dockerfile
    container_name: backend1
    expose:
      - "8080"             
    networks:
      - backendnet

  backend2:
    build:
      context: ./backend/backend2
      dockerfile: Dockerfile
    container_name: backend2
    expose:
      - "8080"
    networks:
      - backendnet

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - backendnet

networks:
  backendnet:
    driver: bridge
